// Code generated by copying from types2 (see cmd/compile/internal/types2/gecko.go).
// It is maintained by hand (not by the go/types generator) because it must use
// go/token positions.

// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements the gecko declare-or-assign helpers used by
// the checker. It mirrors cmd/compile/internal/types2/gecko.go.

package types

import (
	"go/ast"
	"go/token"
	"strings"
)

// geckoFile reports whether the position pos belongs to a gecko (.gk)
// source file.
func (check *Checker) geckoFile(pos token.Pos) bool {
	if check.fset == nil || !pos.IsValid() {
		return false
	}
	return strings.HasSuffix(check.fset.File(pos).Name(), ".gk")
}

// geckoDynamicFile reports whether pos belongs to a gecko source file that
// runs in "dynamic" mode, i.e. whether gecko's dynamic-typing features apply
// at pos. A "typed" project (Config.GeckoTyped) disables them.
func (check *Checker) geckoDynamicFile(pos token.Pos) bool {
	return check.geckoFile(pos) && !check.conf.GeckoTyped
}

// geckoNewVar reports whether any name in lhs is not currently visible
// anywhere in the lexical environment, i.e. whether a gecko `x = e`
// assignment statement one of its lhs names would have to declare.
func (check *Checker) geckoNewVar(lhs []ast.Expr) bool {
	for _, l := range lhs {
		if ident, ok := ast.Unparen(l).(*ast.Ident); ok && ident.Name != "_" && check.lookup(ident.Name) == nil {
			return true
		}
	}
	return false
}

// geckoCompositeType infers the type of a dynamic gecko composite literal
// (typed `[1, 2, 3]` or `{"name": "gecko"}`) from its elements. A list with
// key-value pairs is a map; anything else is a slice. Element, key and value
// types come from the element literals themselves; if elements disagree, or
// a non-literal expression appears, the element (or key/value) type is `any`.
func (check *Checker) geckoCompositeType(e *ast.CompositeLit) (Type, Type) {
	hasKey := false
	for _, el := range e.Elts {
		if _, ok := el.(*ast.KeyValueExpr); ok {
			hasKey = true
			break
		}
	}
	if !hasKey {
		et := check.geckoElemType(e.Elts)
		typ := NewSlice(et)
		return typ, typ
	}
	var kt, vt Type
	for _, el := range e.Elts {
		kv := el.(*ast.KeyValueExpr)
		kt = check.geckoUnify(kt, check.geckoLitType(kv.Key))
		vt = check.geckoUnify(vt, check.geckoLitType(kv.Value))
	}
	typ := NewMap(kt, vt)
	return typ, typ
}

func (check *Checker) geckoElemType(es []ast.Expr) Type {
	var et Type
	for _, e := range es {
		et = check.geckoUnify(et, check.geckoLitType(e))
	}
	return et
}

// geckoUnify folds two candidate types into one. Equal types are kept;
// anything else forces the `any` type. A nil type (the `null` literal)
// contributes nothing.
func (check *Checker) geckoUnify(a, b Type) Type {
	if a == nil {
		return b
	}
	if b == nil {
		return a
	}
	if Identical(a, b) {
		return a
	}
	return universeAny.Type()
}

// geckoLitType reports the inferred type of a single dynamic literal element:
// literals map to their default types, true/false to bool, null to nil, and
// compound literals recursively to their inferred type. Any other expression
// yields `any`.
func (check *Checker) geckoLitType(e ast.Expr) Type {
	switch e := ast.Unparen(e).(type) {
	case *ast.BasicLit:
		switch e.Kind {
		case token.INT:
			return Typ[Int]
		case token.FLOAT:
			return Typ[Float64]
		case token.IMAG:
			return Typ[Complex128]
		case token.CHAR:
			return Typ[Rune]
		case token.STRING:
			return Typ[String]
		}
	case *ast.Ident:
		switch e.Name {
		case "true", "false":
			return Typ[Bool]
		case "null":
			return nil
		}
	case *ast.CompositeLit:
		t, _ := check.geckoCompositeType(e)
		return t
	}
	return universeAny.Type()
}
